steps:
  # 1. Build and Create Release for Frontend
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud deploy releases create "rel-f-${SHORT_SHA}-$$(echo ${BUILD_ID} | cut -c1-8)" \
          --delivery-pipeline="glial-sales-frontend-pipeline" \
          --region="us-central1" \
          --skaffold-file="skaffold.yaml" \
          --source="."
    dir: "sales-research/frontend"

options:
  logging: CLOUD_LOGGING_ONLY
