apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: glial-sales-frontend-pipeline
description: Delivery pipeline for Glial Sales Research Frontend
serialPipeline:
  stages:
    - targetId: frontend-staging
    - targetId: frontend-production
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: frontend-staging
description: Frontend Staging environment
run:
  location: projects/innovize-ai/locations/us-central1
deployParameters:
  frontend_service_name: glial-research-frontend-service-staging
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: frontend-production
description: Frontend Production environment
run:
  location: projects/innovize-ai/locations/us-central1
deployParameters:
  frontend_service_name: glial-research-frontend-service
