"""Initial migration

Revision ID: bc1f87b75c11
Revises: 
Create Date: 2025-01-16 13:36:19.714957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc1f87b75c11'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('sender_email', sa.String(), nullable=False),
    sa.Column('preprocesses_email', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('category', sa.Enum('WARM_UP', 'TRANSACTIONAL', 'MARKETING', 'SALES', 'CUSTOMER_SUPPORT', 'FINANCE_ADMINISTRATIVE', 'LEGAL_COMPLIANCE', 'HR_RECRUITMENT', 'TECHNICAL_SUPPORT', 'EDUCATION_TRAINING', 'SECURITY_ALERT', 'FEEDBACK_REVIEW', 'COMMUNITY_ENGAGEMENT', 'GENERAL_NOTIFICATIONS', 'PROJECT_MANAGEMENT', 'ENQUIRY', 'LOGISTICS', name='categoryenum'), nullable=False),
    sa.Column('intent', sa.Enum('AWARENESS', 'INTEREST', 'CONSIDERATION', 'DECISION', 'DISENGAGED', name='intentenum'), nullable=True),
    sa.Column('pii_detected', sa.Boolean(), nullable=True),
    sa.Column('filtered_content', sa.Text(), nullable=True),
    sa.Column('requires_response', sa.Boolean(), nullable=True),
    sa.Column('escalated_to_human', sa.Boolean(), nullable=True),
    sa.Column('category_confidence_score', sa.Float(), nullable=True),
    sa.Column('email_response_draft', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['public.profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('profiles', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint('profiles_id_fkey', 'profiles', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('profiles_id_fkey', 'profiles', 'users', ['id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.alter_column('profiles', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_table('emails')
    # ### end Alembic commands ###
