"""Add persistent memory and strategic fields to ResearchReport

Revision ID: 072e7c3d35e1
Revises: e0d52411e177
Create Date: 2026-01-23 17:15:07.024715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '072e7c3d35e1'
down_revision: Union[str, Sequence[str], None] = 'e0d52411e177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_reports', sa.Column('follow_up_strategy', sa.Text(), nullable=True))
    op.add_column('research_reports', sa.Column('buyer_journey_analysis', sa.Text(), nullable=True))
    op.add_column('research_reports', sa.Column('meeting_notes', sa.Text(), nullable=True))
    op.add_column('research_reports', sa.Column('lead_company_linkedin_url', sa.Text(), nullable=True))
    op.add_column('research_reports', sa.Column('lead_li_urn', sa.Text(), nullable=True))
    op.add_column('research_reports', sa.Column('extra_metadata', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_reports', 'extra_metadata')
    op.drop_column('research_reports', 'lead_li_urn')
    op.drop_column('research_reports', 'lead_company_linkedin_url')
    op.drop_column('research_reports', 'meeting_notes')
    op.drop_column('research_reports', 'buyer_journey_analysis')
    op.drop_column('research_reports', 'follow_up_strategy')
    # ### end Alembic commands ###
