"""add post_topic_depth to identified_profiles

Revision ID: 09da1a1c1f75
Revises: 6c7ae694c216
Create Date: 2026-03-17 17:16:05.782750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09da1a1c1f75'
down_revision: Union[str, Sequence[str], None] = '6c7ae694c216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identified_profiles', sa.Column('post_topic_depth', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identified_profiles', 'post_topic_depth')
    # ### end Alembic commands ###
