"""Initial migration

Revision ID: 0f5708a34498
Revises: 
Create Date: 2025-12-16 13:47:05.096782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f5708a34498'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('sales_research_report', sa.Text(), nullable=True),
    sa.Column('lead_score_analysis', sa.Text(), nullable=True),
    sa.Column('user_profile_analysis', sa.Text(), nullable=True),
    sa.Column('website_analysis', sa.Text(), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=True),
    sa.Column('project_urgency', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_reports')
    # ### end Alembic commands ###
