"""Add CompetitorAnalysis table

Revision ID: 146d43228c8f
Revises: b74219a59ae2
Create Date: 2026-01-12 11:51:11.261293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '146d43228c8f'
down_revision: Union[str, Sequence[str], None] = 'b74219a59ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_analysis',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('competitor_urls', sa.Text(), nullable=False),
    sa.Column('analysis_report', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_column('organization_settings', 'onboarding_complete')
    # op.drop_column('organization_settings', 'kit_api_key')
    # op.drop_column('organization_settings', 'kit_api_secret')
    # op.drop_column('organization_settings', 'integrations_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_settings', sa.Column('integrations_config', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('organization_settings', sa.Column('kit_api_secret', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organization_settings', sa.Column('kit_api_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organization_settings', sa.Column('onboarding_complete', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_table('competitor_analysis')
    # ### end Alembic commands ###
