"""Add email_history and intent_analysis columns

Revision ID: 18e804dcbe75
Revises: af0a5b0c27cb
Create Date: 2025-12-24 21:46:24.550159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18e804dcbe75'
down_revision: Union[str, Sequence[str], None] = 'af0a5b0c27cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_reports', sa.Column('email_history', sa.Text(), nullable=True))
    op.add_column('research_reports', sa.Column('intent_analysis', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_reports', 'intent_analysis')
    op.drop_column('research_reports', 'email_history')
    # ### end Alembic commands ###
