"""Add hubspot and crm context

Revision ID: 1bcef966ac94
Revises: b8c7afd54d83
Create Date: 2026-02-18 14:07:18.854384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bcef966ac94'
down_revision: Union[str, Sequence[str], None] = 'b8c7afd54d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_context',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('hubspot_contact_id', sa.String(), nullable=True),
    sa.Column('hubspot_company_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('original_company', sa.String(), nullable=True),
    sa.Column('deal_name', sa.String(), nullable=True),
    sa.Column('deal_stage', sa.String(), nullable=True),
    sa.Column('closed_lost_reason', sa.Text(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('extra_metadata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_context_email'), 'crm_context', ['email'], unique=False)
    op.create_index(op.f('ix_crm_context_linkedin_url'), 'crm_context', ['linkedin_url'], unique=False)
    op.add_column('organization_settings', sa.Column('hubspot_access_token', sa.Text(), nullable=True))
    op.add_column('organization_settings', sa.Column('hubspot_sync_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_settings', 'hubspot_sync_enabled')
    op.drop_column('organization_settings', 'hubspot_access_token')
    op.drop_index(op.f('ix_crm_context_linkedin_url'), table_name='crm_context')
    op.drop_index(op.f('ix_crm_context_email'), table_name='crm_context')
    op.drop_table('crm_context')
    # ### end Alembic commands ###
