"""Add headline to IdentifiedProfile

Revision ID: 55310df59e72
Revises: 758dd847d66d
Create Date: 2026-01-19 18:54:12.149563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55310df59e72'
down_revision: Union[str, Sequence[str], None] = '758dd847d66d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identified_profiles', sa.Column('headline', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identified_profiles', 'headline')
    # ### end Alembic commands ###
