"""Add multi-tenant fields and user_settings table

Revision ID: 5f7bf77d386f
Revises: 159d6123038a
Create Date: 2026-02-17 13:22:53.495615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f7bf77d386f'
down_revision: Union[str, Sequence[str], None] = '159d6123038a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_linkedin_url', sa.Text(), nullable=True),
    sa.Column('email_config', sa.Text(), nullable=True),
    sa.Column('icp_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('activities', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.add_column('competitors', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.add_column('identified_profiles', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.add_column('lead_submissions', sa.Column('rep_id', sa.UUID(), nullable=True))
    op.add_column('research_reports', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.add_column('research_reports', sa.Column('icp_context', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_reports', 'icp_context')
    op.drop_column('research_reports', 'created_by_id')
    op.drop_column('lead_submissions', 'rep_id')
    op.drop_column('identified_profiles', 'created_by_id')
    op.drop_column('competitors', 'created_by_id')
    op.drop_column('activities', 'created_by_id')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
