"""Add outreach tracking columns to research_reports

Revision ID: 6c7ae694c216
Revises: 439f18112c0b
Create Date: 2026-03-05 12:38:39.578240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c7ae694c216'
down_revision: Union[str, Sequence[str], None] = '439f18112c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_reports', sa.Column('outreach_status', sa.String(), server_default=sa.text("'not_started'"), nullable=True))
    op.add_column('research_reports', sa.Column('outreach_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('research_reports', sa.Column('is_outreach_edited', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('research_reports', sa.Column('edit_depth_percentage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_reports', 'edit_depth_percentage')
    op.drop_column('research_reports', 'is_outreach_edited')
    op.drop_column('research_reports', 'outreach_started_at')
    op.drop_column('research_reports', 'outreach_status')
    # ### end Alembic commands ###
