"""add profile_metadata to profiles

Revision ID: 70e9558e0cc6
Revises: 168d8aa78d31
Create Date: 2026-04-29 11:39:35.518302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e9558e0cc6'
down_revision: Union[str, Sequence[str], None] = '168d8aa78d31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('profile_metadata', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'profile_metadata')
    # ### end Alembic commands ###
