"""add website to identified_profiles

Revision ID: 885a7d2efdeb
Revises: 9c3904efb4bc
Create Date: 2026-03-04 13:16:54.932613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '885a7d2efdeb'
down_revision: Union[str, Sequence[str], None] = '9c3904efb4bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identified_profiles', sa.Column('website', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identified_profiles', 'website')
    # ### end Alembic commands ###
