"""add_email_id_to_research_report

Revision ID: 913e2401f88e
Revises: 18e804dcbe75
Create Date: 2025-12-25 13:31:53.805377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '913e2401f88e'
down_revision: Union[str, Sequence[str], None] = '18e804dcbe75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_reports', sa.Column('email_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_reports', 'email_id')
    # ### end Alembic commands ###
