"""add_full_name_to_profiles

Revision ID: a23825186bf8
Revises: cc081e72c326
Create Date: 2026-02-17 13:57:17.677755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a23825186bf8'
down_revision: Union[str, Sequence[str], None] = 'cc081e72c326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('full_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'full_name')
    # ### end Alembic commands ###
