"""update research report and settings

Revision ID: e0d52411e177
Revises: fc487ce6b28f
Create Date: 2026-01-22 00:29:17.109925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0d52411e177'
down_revision: Union[str, Sequence[str], None] = 'fc487ce6b28f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_reports', sa.Column('company_stats', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_reports', 'company_stats')
    # ### end Alembic commands ###
