"""Add Competitor model

Revision ID: edadbfe1b194
Revises: 146d43228c8f
Create Date: 2026-01-18 21:14:25.738118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'edadbfe1b194'
down_revision: Union[str, Sequence[str], None] = '146d43228c8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitors',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linkedin_url')
    )
    # op.drop_table('lead_submissions')  <-- REMOVED because it breaks later migrations
    # op.drop_column('research_reports', 'extra_metadata') <-- REMOVED
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_reports', sa.Column('extra_metadata', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_table('lead_submissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('linkedin_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('payload', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('research_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('external_form_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('external_form_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action_type', sa.VARCHAR(), server_default=sa.text("'form_submission'::character varying"), autoincrement=False, nullable=True),
    sa.Column('action_metadata', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('lead_submissions_pkey'))
    )
    op.drop_table('competitors')
    # ### end Alembic commands ###
