"""Add slack_user_id to user_settings

Revision ID: f9d9aa1f52db
Revises: a23825186bf8
Create Date: 2026-02-17 17:28:36.154808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9d9aa1f52db'
down_revision: Union[str, Sequence[str], None] = 'a23825186bf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('slack_user_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user_settings', ['slack_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_settings', type_='unique')
    op.drop_column('user_settings', 'slack_user_id')
    # ### end Alembic commands ###
