"""Add classification fields

Revision ID: fc487ce6b28f
Revises: 55310df59e72
Create Date: 2026-01-19 21:21:56.867110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc487ce6b28f'
down_revision: Union[str, Sequence[str], None] = '55310df59e72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identified_profiles', sa.Column('is_fit', sa.Boolean(), nullable=True))
    op.add_column('identified_profiles', sa.Column('is_competitor', sa.Boolean(), nullable=True))
    op.add_column('identified_profiles', sa.Column('is_decision_maker', sa.Boolean(), nullable=True))
    op.add_column('identified_profiles', sa.Column('fit_reasoning', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identified_profiles', 'fit_reasoning')
    op.drop_column('identified_profiles', 'is_decision_maker')
    op.drop_column('identified_profiles', 'is_competitor')
    op.drop_column('identified_profiles', 'is_fit')
    # ### end Alembic commands ###
