apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: glial-research-frontend-service
  annotations:
    run.googleapis.com/minScale: "0"
    run.googleapis.com/invoker-iam-disabled: true
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "2"
        run.googleapis.com/startup-cpu-boost: "true"
        run.googleapis.com/cpu-throttling: false
    spec:
      containerConcurrency: 80
      containers:
        - image: us-central1-docker.pkg.dev/innovize-ai/sales-research/glial-research-frontend-image:latest
          ports:
            - name: http1
              containerPort: 3000
          resources:
            limits:
              cpu: "1000m"
              memory: "512Mi"
