"""Add kit api key to settings

Revision ID: 2c20b9318e35
Revises: 8ff2f01de2bd
Create Date: 2026-01-04 23:53:38.283482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c20b9318e35'
down_revision: Union[str, Sequence[str], None] = '8ff2f01de2bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_submissions', sa.Column('external_form_id', sa.String(), nullable=True))
    op.add_column('lead_submissions', sa.Column('external_form_name', sa.String(), nullable=True))
    op.add_column('organization_settings', sa.Column('kit_api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_settings', 'kit_api_key')
    op.drop_column('lead_submissions', 'external_form_name')
    op.drop_column('lead_submissions', 'external_form_id')
    # ### end Alembic commands ###
