"""add_scheduling_fields

Revision ID: 2e8a57a02ac1
Revises: 1bcef966ac94
Create Date: 2026-02-23 16:35:20.103371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e8a57a02ac1'
down_revision: Union[str, Sequence[str], None] = '1bcef966ac94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('interval_hours', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('autopilot_rules', sa.Column('interval_hours', sa.Integer(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE autopilot_rules SET interval_hours = 24 WHERE interval_hours IS NULL")
    # Now set it to NOT NULL
    op.alter_column('autopilot_rules', 'interval_hours', nullable=False)
    
    op.add_column('autopilot_rules', sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('autopilot_rules', 'last_run_at')
    op.drop_column('autopilot_rules', 'interval_hours')
    op.drop_table('scheduled_tasks')
    # ### end Alembic commands ###
