"""Add identified_profiles table

Revision ID: 4f29b67c69c9
Revises: edadbfe1b194
Create Date: 2026-01-18 23:20:59.644979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f29b67c69c9'
down_revision: Union[str, Sequence[str], None] = 'edadbfe1b194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identified_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=False),
    sa.Column('comment_history', sa.Text(), nullable=True),
    sa.Column('source_posts', sa.Text(), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('profile_metadata', sa.Text(), nullable=True),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linkedin_url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('identified_profiles')
    # ### end Alembic commands ###
