"""Add selling_profile_json to organization_settings

Revision ID: 5224edc891db
Revises: c310d5b62997
Create Date: 2026-02-13 12:24:08.406433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5224edc891db'
down_revision: Union[str, Sequence[str], None] = 'c310d5b62997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_settings', sa.Column('selling_profile_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_settings', 'selling_profile_json')
    # ### end Alembic commands ###
