"""add_api_keys_to_settings

Revision ID: 67e14073ae29
Revises: 6dd2c6764fbc
Create Date: 2025-12-24 18:01:29.856371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67e14073ae29'
down_revision: Union[str, Sequence[str], None] = '6dd2c6764fbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_settings', sa.Column('tavily_api_key', sa.String(), nullable=True))
    op.add_column('organization_settings', sa.Column('apollo_api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_settings', 'apollo_api_key')
    op.drop_column('organization_settings', 'tavily_api_key')
    # ### end Alembic commands ###
