"""add interaction_history to identified_profiles

Revision ID: 758dd847d66d
Revises: 18c090ca97a1
Create Date: 2026-01-18 23:59:06.633390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '758dd847d66d'
down_revision: Union[str, Sequence[str], None] = '18c090ca97a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identified_profiles', sa.Column('interaction_history', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identified_profiles', 'interaction_history')
    # ### end Alembic commands ###
