"""Add kit api secret

Revision ID: 8b3207d2ffcc
Revises: 2c20b9318e35
Create Date: 2026-01-05 00:08:51.682910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b3207d2ffcc'
down_revision: Union[str, Sequence[str], None] = '2c20b9318e35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_settings', sa.Column('kit_api_secret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_settings', 'kit_api_secret')
    # ### end Alembic commands ###
