"""Add onboarding complete and integrations config

Revision ID: 8ff2f01de2bd
Revises: dc7435f1a97a
Create Date: 2026-01-04 23:25:59.578333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ff2f01de2bd'
down_revision: Union[str, Sequence[str], None] = 'dc7435f1a97a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_settings', sa.Column('integrations_config', sa.Text(), nullable=True))
    op.add_column('organization_settings', sa.Column('onboarding_complete', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_settings', 'onboarding_complete')
    op.drop_column('organization_settings', 'integrations_config')
    # ### end Alembic commands ###
