"""Add fullname and profile_picture_url

Revision ID: a0e2eb0fa557
Revises: 0f5708a34498
Create Date: 2025-12-22 18:45:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a0e2eb0fa557'
down_revision: Union[str, Sequence[str], None] = '0f5708a34498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_reports', sa.Column('fullname', sa.Text(), nullable=True))
    op.add_column('research_reports', sa.Column('profile_picture_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_reports', 'profile_picture_url')
    op.drop_column('research_reports', 'fullname')
    # ### end Alembic commands ###
