"""Add email_config and crm_config to OrganizationSettings

Revision ID: af0a5b0c27cb
Revises: 67e14073ae29
Create Date: 2025-12-24 20:52:42.408775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af0a5b0c27cb'
down_revision: Union[str, Sequence[str], None] = '67e14073ae29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_settings', sa.Column('email_config', sa.Text(), nullable=True))
    op.add_column('organization_settings', sa.Column('crm_config', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_settings', 'crm_config')
    op.drop_column('organization_settings', 'email_config')
    # ### end Alembic commands ###
