"""Add CompetitorAnalysis table

Revision ID: b74219a59ae2
Revises: 8b3207d2ffcc
Create Date: 2026-01-12 11:47:29.239723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b74219a59ae2'
down_revision: Union[str, Sequence[str], None] = '8b3207d2ffcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_submissions', sa.Column('action_type', sa.String(), server_default=sa.text("'form_submission'"), nullable=True))
    op.add_column('lead_submissions', sa.Column('action_metadata', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_submissions', 'action_metadata')
    op.drop_column('lead_submissions', 'action_type')
    # ### end Alembic commands ###
