"""add_cso_strategic_briefing

Revision ID: c310d5b62997
Revises: d40ad0cfa79c
Create Date: 2026-02-12 18:12:03.455472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c310d5b62997'
down_revision: Union[str, Sequence[str], None] = 'd40ad0cfa79c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'intent',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('activities', 'sentiment',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('identified_profiles', 'intent',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('identified_profiles', 'sentiment',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('research_reports', 'recent_posts')
    op.add_column('research_reports', sa.Column('cso_strategic_briefing', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_reports', sa.Column('recent_posts', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('identified_profiles', 'sentiment',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('identified_profiles', 'intent',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('activities', 'sentiment',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('activities', 'intent',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('research_reports', 'cso_strategic_briefing')
    # ### end Alembic commands ###
