"""added_slack_integration

Revision ID: d40ad0cfa79c
Revises: a38f5a96beb1
Create Date: 2026-02-09 13:50:19.633599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd40ad0cfa79c'
down_revision: Union[str, Sequence[str], None] = 'a38f5a96beb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_submissions', sa.Column('action_type', sa.String(), server_default=sa.text("'form_submission'"), nullable=True))
    op.add_column('lead_submissions', sa.Column('action_metadata', sa.Text(), nullable=True))
    op.add_column('lead_submissions', sa.Column('email_history', sa.Text(), nullable=True))
    op.add_column('lead_submissions', sa.Column('intent_analysis', sa.Text(), nullable=True))
    op.add_column('lead_submissions', sa.Column('extra_metadata', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_submissions', 'extra_metadata')
    op.drop_column('lead_submissions', 'intent_analysis')
    op.drop_column('lead_submissions', 'email_history')
    op.drop_column('lead_submissions', 'action_metadata')
    op.drop_column('lead_submissions', 'action_type')
    # ### end Alembic commands ###
