"""Add multi-tenant fields and user_settings table

Revision ID: ddc58505201b
Revises: 5f7bf77d386f
Create Date: 2026-02-17 13:24:07.763100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddc58505201b'
down_revision: Union[str, Sequence[str], None] = '5f7bf77d386f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
