apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: glial-sales-frontend-pipeline
description: Delivery pipeline for Glial Sales Research Frontend
serialPipeline:
  stages:
    - targetId: frontend-staging
      profiles:
        - staging
    - targetId: frontend-production
      profiles:
        - production
    - targetId: frontend-trial
      profiles:
        - trial
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: frontend-staging
description: Frontend Staging environment
run:
  location: projects/innovize-ai/locations/us-central1
deployParameters: {}
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: frontend-trial
description: Frontend Trial environment
run:
  location: projects/innovize-ai/locations/us-central1
deployParameters: {}
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: frontend-production
description: Frontend Production environment
run:
  location: projects/innovize-ai/locations/us-central1
deployParameters: {}
