apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: glial-sales-backend-pipeline
description: Delivery pipeline for Glial Sales Research Backend
serialPipeline:
  stages:
    - targetId: backend-staging
    - targetId: backend-production
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: backend-staging
description: Backend Staging environment
run:
  location: projects/innovize-ai/locations/us-central1
deployParameters:
  backend_service_name: glial-research-backend-service-staging
  DB_SCHEMA: staging
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: backend-production
description: Backend Production environment
run:
  location: projects/innovize-ai/locations/us-central1
deployParameters:
  backend_service_name: glial-research-backend-service
  DB_SCHEMA: public
