apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: glial-sales-backend-pipeline
description: Delivery pipeline for Glial Sales Research Backend
serialPipeline:
  stages:
    - targetId: backend-staging
      profiles:
        - staging
    - targetId: backend-production
      profiles:
        - production
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: backend-staging
description: Backend Staging environment
run:
  location: projects/innovize-ai/locations/us-central1
deployParameters: {}
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: backend-production
description: Backend Production environment
run:
  location: projects/innovize-ai/locations/us-central1
deployParameters: {}
