apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: glial-sales-research-backend
build:
  artifacts:
    - image: glial-research-backend-image
      context: .
manifests:
  rawYaml:
    - backend.yaml
deploy:
  cloudrun: {}
