apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: glial-sales-research-backend
build:
  artifacts:
    - image: gcr.io/innovize-ai/glial-research-backend-image
      context: .
profiles:
  - name: staging
    manifests:
      rawYaml:
        - deploy/backend-staging.yaml
  - name: production
    manifests:
      rawYaml:
        - deploy/backend-production.yaml
deploy:
  cloudrun: {}
