"""add thread idto email table

Revision ID: d87e78ca3fdb
Revises: bc1f87b75c11
Create Date: 2025-01-28 21:45:17.497133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd87e78ca3fdb'
down_revision: Union[str, None] = 'bc1f87b75c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('thread_id', sa.String(), nullable=False))
    op.alter_column('emails', 'subject',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('emails', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('emails_user_id_fkey', 'emails', type_='foreignkey')
    op.create_foreign_key(None, 'emails', 'profiles', ['user_id'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('profiles_id_fkey', 'profiles', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('profiles_id_fkey', 'profiles', 'users', ['id'], ['id'], referent_schema='auth', onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.create_foreign_key('emails_user_id_fkey', 'emails', 'profiles', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('emails', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('emails', 'subject',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('emails', 'thread_id')
    # ### end Alembic commands ###
