apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: glial-research-backend-service
  annotations:
    run.googleapis.com/minScale: "1"
    run.googleapis.com/cpu-throttling: false
    run.googleapis.com/invoker-iam-disabled: false
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: false
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      timeoutSeconds: 3600
      containers:
        - image: us-central1-docker.pkg.dev/innovize-ai/sales-research/glial-research-backend-image:latest
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits:
              cpu: "1000m"
              memory: "1Gi"
          env:
            - name: ENVIRONMENT
              value: production
            - name: DB_SCHEMA
              value: public
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: PYTHONPATH
              value: "/app"
